- name: Set up local development environment
  hosts: local
  roles:
    # Tag each role so that we can select individual roles to run with ansible-playbook --tags
    - { role: package_manager, tags: ["package_manager", "bootstrap"] }
    - { role: python, tags: ["python"] }
    - { role: macos, tags: ["macos"], when: ansible_os_family == "Darwin" }
